name: Release to dev
on:
  push:
    branches:
      - dev-cere
  workflow_dispatch:

jobs:
  build_backend_cerestats_api:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-push-docker.yaml@1.0.0
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      org: cerebellumnetwork
      environment: dev
      image: crb-cerestats-api
      repository: crb-cerestats-api
      file: ./api/Dockerfile
    secrets: inherit

  build_backend_cerestats_crawler:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-push-docker.yaml@1.0.0
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      org: cerebellumnetwork
      environment: dev
      image: crb-cerestats-crawler
      repository: crb-cerestats-crawler
      file: ./backend/docker/crawler/Dockerfile
    secrets: inherit

  deploy_backend_cerestats_api:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-with-helm.yaml@1.0.0
    needs: build_backend_cerestats_api
    with:
      runs-on: '["self-hosted", "cere-network-dev-deployer"]'
      helm-repo-path: cerestats/cerestats-api
      helm-release: cerestats-api
      namespace: cerestats
      tag: ${{ needs.build_backend_cerestats_api.outputs.version }}
      environment: dev
    secrets: inherit

  deploy_backend_cerestats_crawler:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-with-helm.yaml@1.0.0
    needs: build_backend_cerestats_crawler
    with:
      runs-on: '["self-hosted", "cere-network-dev-deployer"]'
      helm-repo-path: cerestats/cerestats-crawler
      helm-release: cerestats-crawler
      namespace: cerestats
      tag: ${{ needs.build_backend_cerestats_crawler.outputs.version }}
      environment: dev
    secrets: inherit

  build_and_deploy_frontend:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-upload-static.yaml@master
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      build_container: 'node:14-buster-slim'
      deploy_container: 'ubuntu:20.04'
      install_packages_command: 'cp -rf frontend/frontend.config-cere-dev.js frontend/frontend.config.js; yarn install'
      build_command: 'yarn workspace frontend generate'
      path_to_static_files_to_upload: 'frontend/dist'
    secrets:
      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_NETWORK_AWS_ACCESS_KEY_ID }}
      NETWORK_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_NETWORK_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEV }}
      CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID_DEV }}
