name: Release to dev
on:
  push:
    branches:
      - dev-cere
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_backend_cerestats_api:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    with:
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: stats-api
      file: ./api/Dockerfile
    secrets: inherit

  build_and_deploy_backend_cerestats_crawler:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    with:
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: stats-crawler
      file: ./backend/docker/crawler/Dockerfile
    secrets: inherit

  build_and_deploy_frontend:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:14-buster-slim'
      install_packages_command: 'cp -rf frontend/frontend.config-cere-dev.js frontend/frontend.config.js; yarn install'
      build_command: 'yarn workspace frontend generate'
      path_to_static_files_to_upload: 'frontend/dist'
      aws_account_id: ${{ vars.STG_NETWORK_AWS_ACCOUNT_ID }}
      s3_bucket_name: "stats.dev.cere.network"
