name: Release to dev
on:
  push:
    branches:
      - dev-cere
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build_backend_cerestats_api:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@1.3.0
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: stats-api
      file: ./api/Dockerfile
    secrets: inherit
    
  build_backend_cerestats_crawler:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@1.3.0
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      environment: dev
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: stats-crawler
      file: ./backend/docker/crawler/Dockerfile
    secrets: inherit
